spring.application.name=phamhaonam1
server.port=8081
# spring.datasource.url=jdbc:mysql://localhost:3306/hocsinh?useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=nam123
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:sqlserver://RUSSELL\\SQLEXPRESS04\\MSSQLSERVER1:1433;encrypt=true;trustServerCertificate=true;databaseName=hocsinh;integratedSecurity=true;
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false